# Interop Mobile Money Simulator CircleCI

version: 2.1
orbs:
  coverage-reporter: codacy/coverage-reporter@10.0.3
executors:
  # Define a machine who has support for docker compose 3.7
  standard:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
  test:
    docker:
      - image: gsmainclusivetechlab/interop-php-fpm:latest
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: developer
          MYSQL_DATABASE: itp-mmo-api-control
          MYSQL_USER: itp-mmo-api-control
          MYSQL_PASSWORD: developer
    working_directory: ~/repo
jobs:
  build:
    executor: standard
    
    steps:
      - checkout

      - run: 
          name: Generate configuration files
          command: make init

      - run: 
          name: Run docker containers
          command: | 
            make run
            sleep 15
          
      - restore_cache: 
          keys:
            - composer-v1-{{ checksum "src/composer.lock" }}
            - composer-v1-

      - run: 
          name: Install Componser dependecies
          command: make install
      
      - save_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor

      - run: 
          name: Check installation
          command: |
            FILE=./runtime/installed
            if test -f "$FILE"; then
                echo "Installation succesful"
            else 
                echo "Installation fail"
                exit 2
            fi

  test-run:
    executor: test
    
    steps:
      - checkout
      
      - run: 
          name: Generate configuration files
          command: make init
            
      - restore_cache: 
          keys:
            - composer-v1-test{{ checksum "src/composer.lock" }}
            - composer-v1-test

      - run: 
          name: Install Componser dependecies
          command: |
            sleep 15
            cd src
            make install
      
      - save_cache:
          key: composer-v1-test{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor

      - run:
          name: Run Tests
          command: |
            cd src
            make test
          
      - run:
          name: Run Tests Coverage
          command: |
            cd src
            make test-coverage
 
      - store_test_results:
          path: src/tests/results
      - store_artifacts:
          path: src/tests/results
          
      - persist_to_workspace:      
          root: ~/repo/src/tests
          paths:
            - results
          
  test-coverage-codacy:
    docker:
      - image: gsmainclusivetechlab/interop-php-fpm:latest
    working_directory: ~/repo
    
    steps:
      - attach_workspace:
          at: ~/repo/src/tests
          
      - coverage-reporter/send_report:
          coverage-reports: src/tests/results/coverage-report-clover/clover.xml
          project-token: $CODACY_PROJECT_TOKEN
      
      - run:
          name: Copy codacy json report to artifact
          command: sudo cp /var/tmp/codacy-coverage-*.json ~/repo/src/tests/results/
          
      - store_test_results:
          path: src/tests/results
      - store_artifacts:
          path: src/tests/results
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - test-run:
          filters:
            branches:
              only:
                - master
                - develop
      - test-coverage-codacy:
          filters:
            branches:
              only:
                - master
                - develop
          requires:
            - test-run
